name: Warmup Service
on:
  schedule:
    - cron: '*/14 * * * *'
jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:
      - name: REST API with curl
        run: |
          curl -X GET "https://whats-event.onrender.com/events" -H "accept: application/json"