name: Run Daily to Trigger Deployment
on:
  schedule:
    # - cron: '0 7 * * *'   # 7 utc 10 eat
    # - cron: "*/5 * * * *"
    - cron: "*/12 6-23,0 * * *"
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm install
      - name: Run app
        run: node index.js
      # Trigger deploy webhook

      - name: HTTP Request Action
        uses: fjogeleit/http-request-action@v1.14.0
        with:
          url: https://whats-event.onrender.com/events
          method: POST